### ISSUE TITLE
For those who want to use this app

### ISSUE THREAD

**Issue by BlackCharon142** [TKMAX777/RemoteRelativeInput#1]
So the Instructions were a little too complicated for the average user so I decided to help you out a little since this is kind of the only working solution I've found

First of all, these are the things you need to install
1-[OpenSSH Client](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) (on host and client)
2-[OpenSSH Server](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) (on host and client)
3-[GO](https://go.dev/doc/install) for your platform (on host and client)
4-[Git](https://gitforwindows.org/) (on client)

after downloading and installing all the above, you need to open CMD as Administrator and then run the following commands (on host and client)
`go install github.com/TKMAX777/RemoteRelativeInput/cmd/RelativeInputServer@latest`
`go install github.com/TKMAX777/RemoteRelativeInput/cmd/RelativeInputWorker@latest`
`go install github.com/TKMAX777/RemoteRelativeInput/cmd/RelativeInputClient@latest`

Open Remote Desktop Connection and connect to your server like usual and have it in Maximize Windowed(NOT FULL SCREEN)
Then open CMD as Administrator on Host Machine and run the following command

`start /d "C:\Users\<UserName>\go\bin" RelativeInputWorker.exe`
*replace The <UserName> With the name of the folder of your account located in C:\Users

Then in the Client Machine open Git Bash and type the following command
`CLIENT_NAME='<HostIP> - Remote Desktop Connection' RelativeInputClient.exe |ssh <HostUserName>@<HostIP> "C:\Users\<HostFolderName>\go\bin\RelativeInputServer.exe"`
*replace The <HostFolderName> With the name of the folder of your account located in C:\Users
*replace <HostUserName> With the Host username
*replace <HostIP> With the IP of your host

Hit Enter
If your account has a password, ignore the message box and click on the git bash tab, and type in your password
Then you should get a message box on the host machine(Hit Yes) and it should say `Start Connection`
After that go back and hit Ok on the message box you saw earlier
If your mouse disappeared hit F8 and go back to your Remote Desktop Connection Then choose RDP Input Wrapper and hit F8

This was the exact steps I had to follow through
If you have any question, ask them and I'll do my best to answer

If I found a better alternative I'll Post it here as well

**Comment by TKMAX777** [comment]
Thank you!
Can I copy & paste your instructions to readme?

**Comment by Arbross** [comment]
Is CLIENT_NAME naming of a rdp window? I tried to enter smth like this and I got error. And there may be not only 192.168... , right?

**Comment by TKMAX777** [comment]
That's right.You must enter the window name of the remote desktop client.

You must enter the window name of the remote desktop client.

This may therefore be an IP address other than the address starting with 192.168, or it may be a domain name.

**Comment by Arbross** [comment]
I tried to enter the name of the window, filled other fields and got this : `'CLIENT_NAME' is not recognized as an internal or external command, operable program or batch file.`

**Comment by TKMAX777** [comment]
As far as I have verified, it works even on localhost.
Perhaps the command is wrong.

Is it really like this?

`CLIENT_NAME='localhost:**** - Remote Desktop Connection' RelativeInputClient.exe | ssh 
 <HostUserName>@<HostIP> "C:\Users\<HostFolderName>\go\bin\RelativeInputServer.exe"`

Actually, I am running in a Japanese environment, so I am not sure if the remote desktop window names really appear that way (`localhost:**** - Remote Desktop Connection`) in English settings.

**Comment by TKMAX777** [comment]
Maybe you are using Powershell or a command prompt instead of Git bash.

This program will not work properly in PowerShell.

For it to work properly, you need to run it from a command prompt or Git Bash.

With Git Bash, you can run it with the same command as before, and to run it with Command Prompt, you need to type this:

```
set CLIENT_NAME=localhost:**** - Remote Desktop Connection
RelativeInputClient.exe   | ssh <HostUserName>@<HostIP> "C:\Users\<HostFolderName>\go\bin\RelativeInputServer.exe"
```

**Comment by Arbross** [comment]
Yes, thank you i userd cmd instead Git Bash. App started. It wrote me that is connected but in the same MineCraft it isn't work(the same fast mouse), window is maximaze. Do you have any ideas, what am I doing wrong? Thank you

**Comment by TKMAX777** [comment]
A little more detail is needed to solve the problem.

After selecting the Yes/No dialog for the destination, did you press OK on the confirmation dialog for the client?

If it worked, the output should be like this:

- Local Mechine

```
Start Connection
Ready for sending messages
```

- Remote Machine

```
Start Connection
```

**Comment by BlackCharon142** [comment]
> Thank you!
> 
> Can I use your instructions for readme.md?

Yeah sure

**Comment by TKMAX777** [comment]
I updated the readme.
If the readme is ok, I would like to close this issue once the Arbross issue is resolved.

**Comment by TKMAX777** [comment]
Is the RDP Input Wrapper window visible?
Also, was the mouse cursor pinned by the program (i.e., did you use the F8 key)?

**Comment by Arbross** [comment]
Yes, it was visible(on top of the RDP). I clicked mouse F8 there

**Comment by TKMAX777** [comment]
If you are playing Minecraft, after restarting the game, select the RDP Input Wrapper window and try pressing the F8 key again.

In other words, switch to absolute input by entering the F8 key the first time, close the Minecraft menu, switch to the play screen, then select the RDP Input Wrapper and enter the F8 key. Try switching to relative input mode.

**Comment by TKMAX777** [comment]
No problem.
I will note this in the readme.
