### ISSUE TITLE
Can't connect (language and forgot it had to be minimized)

### ISSUE THREAD

**Issue by Nikki-Devil** [TKMAX777/RemoteRelativeInput#7]
I tried to make this work and I'm at the last step : connect to my server (Linux Ubuntu)

When I try to connect using the command on the Windows CMD I have this :

"
C:\_[Folder]_>set CLIENT_NAME=[ServerIP/URL] - Remote Desktop Connection

C:\_[Folder]_>RelativeInputClient.exe   | ssh [ServerUserName]@[ServerIP/URL] /home/_[ServerUserName]_/go/bin/RelativeInputServer
Password: _[I enter the [ServerUserName] Password before clicking "OK" on the popup]_
panic: NilWindowHandler

goroutine 1 [running]:
github.com/TKMAX777/RemoteRelativeInput.StartClient()
        C:/Users/_[UserName]_/go/pkg/mod/github.com/!t!k!m!a!x777/!remote!relative!input@v1.0.10/windows.go:54 +0x386
main.main()
        C:/Users/_[UserName]_/go/pkg/mod/github.com/!t!k!m!a!x777/!remote!relative!input@v1.0.10/cmd/RelativeInputClient/RelativeInputClient.go:6 +0x17

C:\_[Folder]_>
"

I supposed it could be that I need a password to connect to my ssh/session but I can't have any compromises on this
Also, I'm sure about the password (and it doesn't show when typing it, which seems normal)

**Comment by TKMAX777** [comment]
NilWindowHandler is usually raised when the RDP client fails to find a window.

Check once again that the CLIENT_NAME variable you set exactly matches the window title of the RDP client.

If the configured language of Windows is not US, then the title may not be Remote Desktop Connection.

If you are confident in that setup, could you please let me know the result of the following

```cmd
echo CLIENT_NAME=%CLIENT_NAME%
```

**Comment by Nikki-Devil** [comment]
C:_[Folder]_>echo CLIENT_NAME=%CLIENT_NAME%
CLIENT_NAME=[ServerIP/URL] - Remote Desktop Connection

I will change my system language to test if it fix it

**Comment by TKMAX777** [comment]
Actually, ,my system language is Japanese, so I always set like this: 
 "localhost:30000 - リモート デスクトップ接続"

![image](https://user-images.githubusercontent.com/49893182/206738241-3c5527d0-1143-4d9c-9622-f204d4bd1579.png)

You must type the exact window name that appears at the top of the RDP window.

**Comment by Nikki-Devil** [comment]
Thanks !
I'm checking if it works but it seems to be doing it !
I just didn't had the right RDP name (since I had a french system) and I forgot the RDP couldn't be in fullscreen in order to work

I now have another problem, my inputs aren't going on the server
But it may be because I use and ARM processor and not an amd64 one if your program isn't compiled to it (go, openssh and my remote desktop program are)

**Comment by TKMAX777** [comment]
Hmmm. This could really be the reason for this, but in case it is, here are some other possible causes.

Actually, in Japanese environment, it is acknowledged that using Microsoft's official Japanese IME does not work well or otherwise degrades performance.

I don't know if that happens in French, as I have never tried it, but if possible, could you try it with the ENG input settings?
![image](https://user-images.githubusercontent.com/49893182/206827672-01089e20-66ac-43e9-bff5-0723b2a96d70.png)

**Comment by TKMAX777** [comment]
In the first place, I feel like we need to isolate the problem of whether we are not sending through the SSH tunnel or not getting the input correctly, so I would like to have the program run on its own as follows and see if the message flows.

```cmd
set CLIENT_NAME=*****
RelativeInputClient.exe 
```

**Comment by Nikki-Devil** [comment]
Okay, sorry for the delay I needed to reinstall my server entirely and I changed my whole client system to EN_us
Doing what you asked give me this :

C:\WINDOWS\system32>set CLIENT_NAME=***** && RelativeInputClient.exe
panic: NilWindowHandler

goroutine 1 [running]:
github.com/TKMAX777/RemoteRelativeInput.StartClient()
        C:/Users/[ClientUser]/go/pkg/mod/github.com/!t!k!m!a!x777/!remote!relative!input@v1.0.10/windows.go:54 +0x386
main.main()
        C:/Users/[ClientUser]/go/pkg/mod/github.com/!t!k!m!a!x777/!remote!relative!input@v1.0.10/cmd/RelativeInputClient/RelativeInputClient.go:6 +0x17


Also, rigth now I use an ssh key to use ssh, giving the key inside the C:/Users/[ClientUser]/.ssh/known_hosts seems to have helped since... well... the RelativeInputClient.exe launches once again but now it crashes on the client
The output it gives while running is this :

C:\WINDOWS\system32>set CLIENT_NAME=[ServerIP/URL] - Remote Desktop Connection

C:\WINDOWS\system32>RelativeInputClient.exe | ssh [ServerUser]@[ServerIP/URL] /home/nikki-su/go/bin/RelativeInputServer

The authenticity of host '[ServerIP/URL] ([ServerIP])' can't be established.
ECDSA key fingerprint is SHA256:[SHA256].
Are you sure you want to continue connecting (yes/no/[fingerprint])? Ready for sending messages

**Comment by TKMAX777** [comment]
You are getting a fingerprint confirmation message on the latter, did you enter yes to this?

If you have already specified it in known_hosts, then it is possible that this message is a mistake in setting the fingerprint.


By the way, I can confirm that "Ready for sending messages" is displayed here. Does a window appear at this time?

If the window is appeared, could you try executing without ssh after specifying CLIENT_NAME as well as this?

```
set CLIENT_NAME=*****
RelativeInputClient.exe 
```

It is very strange that the NilWindowHandler panic is occurring in the former while the latter is working fine.

**Comment by Nikki-Devil** [comment]
Okay so first of all it seems that the problem is resolved

Now, the problem seems to be coming from the fact I didn't see I had a prompt to interact with on the CMD (for the fingerprint, you made me realize it), before asking me for the User's Password

It's kind of annoying to have to confirm the fingerprint and then the password but it works so that's cool
